version: "3.9"
services:
  go-rest-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - database
    ports:
      - 9090:9090
    volumes:
      - .:/code/

  database:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: food
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./tmp/db/data:/var/lib/mysql

  database-gui-manager:
    image: adminer:fastcgi
    restart: always
    ports:
      - "8282:8282"
    command:
      - 'php'
      - '-S'
      - '[::]:8282'
      - '-t'
      - '/var/www/html'
    entrypoint:
      - 'entrypoint.sh'
      - 'docker-php-entrypoint'
